### DISCUSSION TITLE
Could not create paste

### DISCUSSION THREAD

**Discussion by kWAYTV** [PrivateBin/PrivateBin#1292] [Q&A] [answered]
### Describe the problem/question

 Could not create paste: Error saving paste. Sorry.

### Did you use the FAQ section?

- [X] Yes, I have read [the FAQ](https://github.com/PrivateBin/PrivateBin/wiki/FAQ) and I found no solution/answer there.

### What you did?

Docker Compose File
```yml
version: '3.8'
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    restart: always
    read_only: true
    ports:
      - "8055:8080"
    volumes:
      - /home/kway/docker/privatebin/data:/srv/data
```
Folder perms
![image](https://github.com/PrivateBin/PrivateBin/assets/55437151/7246c706-5ade-4e74-8aaa-862ba90746f1)

Nginx proxy:
![image](https://github.com/PrivateBin/PrivateBin/assets/55437151/25e482fc-1691-4d48-b37b-ba781f92f0d0)

Error
`2024/04/26 07:35:29 [error] 22#22: *7 FastCGI sent in stderr: "PHP message: failed to store the server salt, delete tokens, traffic limiter and user icons won't work; PHP message: failed to store the traffic limiter, it probably contains outdated information; PHP message: failed to store the purge limiter, skipping purge cycle to avoid getting stuck in a purge loop; PHP message: PHP Warning:  mkdir(): Permission denied in /srv/lib/Data/Filesystem.php on line 98" while reading response header from upstream, client: 172.19.0.3, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "paste.kway.club"`

### Server address

https://paste.kway.club

### Server OS

Ubuntu 22.04

### Webserver

Nginx

### PrivateBin version

Latest

### Browser and version

Brave

### Local operating system and version

Windows 11

### Issue reproducibility

No, I cannot reproduce it on https://privatebin.net.

**Comment by ppfeufer** [comment]
See "Fix Permissions" section » https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/
Maybe that helps.

**Comment by kWAYTV** [comment, marked as answer]
> See "Fix Permissions" section » https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/ Maybe that helps.

Fixed it by creating a volume and mapping it to the container like so:

Creating the volume
```bash
docker volume create privatebin_data
```

Binding it to the container
```yml
version: '3.8'
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    restart: always
    read_only: true
    ports:
      - "8082:8080"
    volumes:
      - privatebin_data:/srv/data

volumes:
  privatebin_data:
    driver: local
```

Thanks to my friend C for the help.
