### ISSUE TITLE
FR: Ability to configure the app fully via environment variables

### ISSUE THREAD

**Issue by samip5** [PrivateBin/PrivateBin#1073]
## What is the feature about?

Ability to configure the container in a stateless manner

## What would it require?

It would require the ability to specify all the things in the config file via environment variables.

## Extra context

This would be a huge improvement for a Kubernetes environment.

**Comment by joeskeen** [comment]
This feels like a wider scope than #1048 but I think it gets at the heart of the same thing. 

I would like to run this in a container without needing to mount a config volume or baking settings into my own image (it's easier to trust an app that you know is unmodified, running from the official image), and the way to do that in the container world would be environment variables.

As far as doing it in a backwards-compatible way (as mentioned by @elrido [here](https://github.com/PrivateBin/PrivateBin/issues/1048#issuecomment-1404846659)), I've looked through how the config is applied and I'll have to do more testing but I think I can implement this in the following way:

* Every setting starts out set to the value defined in the [default configuration](https://github.com/PrivateBin/PrivateBin/blob/f8c2f58604a93f97e823990be9772ce9e0714944/lib/Configuration.php#L37)
* If the custom config file `cfg/conf.php` exists, it's read/parsed as INI file (as it currently is)
  - for each setting set in that file, it overwrites the setting populated by the default
* Then the environment is checked for each setting, which settings would be named by convention (for example, `_configuration['main']['name']` could translate to the environment variable `PRIVATEBIN_MAIN_NAME`. If the environment variable is set, it would overwrite the setting populated by either the defaults.

That way, all your settings would effectively be the environment variables, with a fallback of the custom config, with a fallback of the defaults.

**Comment by elrido** [comment]
Serious question: Could you point me at some articles that explain benefits of using environment variables in a container environment over files?

I was always told that using config files attached read-only to a container are considered safer than using environment variables that may influence all kinds of services before reaching your web app, [can't be read in a thread-safe way on Linux](http://www.club.cc.cmu.edu/~cmccabe/blog_the_setenv_fiasco.html) and expose you to additional risks like [injecting commands](https://int0x33.medium.com/day-29-set-user-id-environment-variable-injection-path-user-for-linux-priv-esc-ea6c0adc19b8) or [buffer overflows](https://owasp.org/www-community/attacks/Buffer_Overflow_via_Environment_Variables). A read-only file would not be able to get manipulated from an exploited application (while env vars can be set at run-time) and at least we only open ourselves to attacks possible due to flaws of PHP's ini parser. And in Kubernetes, either env vars or files can be attached to a pod using [secrets](https://kubernetes.io/docs/concepts/configuration/secret/), so AFAIK they are both equally (in-)conveniant. Am I overthinking this or simply not aware of some crucial benefit of env vars over read-only-files?

**Comment by joeskeen** [comment]
I'm not sure I can authoritatively prove that there are any benefits of using one over the other, but for people that have built their systems around environment variable configuration, it can be painful if there isn't a way to use them. That's why I was hoping my proposal could equally accommodate either use case.

**Comment by elrido** [comment]
I feel there is a learning opportunity for me here. As a more concrete example, here is how I have run the PB image with a custom config on k3s environment (I did this to [test the darkmode config in issue 167](https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/167#issuecomment-1696095352)):

```
---
apiVersion: v1
kind: Secret
metadata:
  name: privatebin-config
data:
  conf.php: |
    ;<?php http_response_code(403); /*
    [main]
    template = "bootstrap-dark"
    syntaxhighlightingtheme = "sons-of-obsidian"
    [model]
    [model_options]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin-deployment
  labels:
    app: privatebin
spec:
  volumes:
    - name: cfg
      secret:
        secretName: privatebin-config
[...]
  replicas: 3
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 82
        fsGroup: 82
      containers:
      - name: privatebin
        image: privatebin/nginx-fpm-alpine:stable
        ports:
        - containerPort: 8080
[...]
        volumeMounts:
        - mountPath: /srv/cfg
          name: cfg
[...]
```

Hypothetically speaking, if we'd had env var support, here is how I assume the k8s YAML would look like:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: privatebin-config
data:
  template: "bootstrap-dark"
  syntaxhighlightingtheme: "sons-of-obsidian"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin-deployment
  labels:
    app: privatebin
spec:
  volumes:
[...]
  replicas: 3
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 82
        fsGroup: 82
      containers:
      - name: privatebin
        image: privatebin/nginx-fpm-alpine:stable
        ports:
        - containerPort: 8080
        env:
        - name: TEMPLATE
          valueFrom:
            secretKeyRef:
              name: privatebin-config
              key: template
        - name: SYNTAXHIGHLIGHTINGTHEME
          valueFrom:
            secretKeyRef:
              name: privatebin-config
              key: syntaxhighlightingtheme
        - name: TZ
          value: Antarctica/South_Pole
        - name: PHP_TZ
          value: Antarctica/South_Pole
[...]
```

Is this what you would imagine doing or do you configure/apply your env vars differently?

Using a ConfigMap instead of a Secret would not make much difference syntactically, but since the config might contain a DB credential, a secret probably makes more sense to use, here.

To me, both of these are just a single YAML file in my config management (possibly a templated one, for injecting values from outside the role/module). The env var also seems like a more complicated way of using these, hence I assume I may be using them wrong or in a non-efficient way and therefore my question.
