### ISSUE TITLE
bs5 feedback

### ISSUE THREAD

**Issue by FingerlessGlov3s** [PrivateBin/PrivateBin#1339]
## The problem
The new bs5 template has fixed width containers for the content of the webpage, where as the old bootstrap theme used to utilise the whole width of the browser. Also when the width is limited it makes the navbar items look strange as they are not in align with the page content.

Utilising the full width of the browser makes more sense when sharing code, less scrolling required, for long lines of code. I personally don't see a benefit in limiting the width of the page.

## The solution
Change `section` elements of the page from using `container` to `container-fluid` class.

## Alternatives
Use old theme, or create your own custom theme based on bs5 to change the class name

**Comment by ppfeufer** [comment]
Same for the `footer` element …

**Comment by elrido** [comment]
This seems to be a choice of the bootstrap framework. Looking at the CSS rules they provide for the `.container` class, we see in bootstrap 3:

```css
@media (min-width: 992px)
.container {
  width: 970px;
}
@media (min-width: 768px)
.container {
  width: 750px;
}
```
While in bootstrap 5 it is:
```css
@media (min-width: 992px)
.container, .container-lg, .container-md, .container-sm {
  max-width: 960px;
}
@media (min-width: 768px)
.container, .container-md, .container-sm {
  max-width: 720px;
}
@media (min-width: 576px)
.container, .container-sm {
  max-width: 540px;
}
```

Changing this to the `.container-fluid` classes would change it to 100%.

Edit: I found an old PR that addressed this default behavior for the bootstrap 3 template in #501 and here is how the custom CSS looked like:

```css
/* address 2K or 4K monitors when using bootstrap 3 */
@media (min-width: 1280px) {
	.container {
		width: 100%;
		padding-left: 4ch;
		padding-right: 4ch;
	}
}
```
We should forward-port this to the new template, since the goal is to replicate the older one, but using the new release of bootstrap.
