### ISSUE TITLE
provide a base path for links only

### ISSUE THREAD

**Issue by parisni** [PrivateBin/PrivateBin#1450]
## The problem

I have a privatebin instance, (example.org) and I wan't to add authentication so that only several people can upload stuff. Also I wan't anybody to access the privatebin resulting links (=public access).

So far, links are in the form `example.org?key`. It would make my life easier if links could be turned in the form `example.org/link?key` bcoz in that case I could disable the auth for any path = `link` instead of disabling the auth "when there is a http query in the same root"

For eg with nginx the former could be written like that
```
location / {
auth_request some-auth;
proxy_path localhost:8080;
}
location /link {
auth_request off;
proxy_path localhost:8080;
}
```

for the latter (which is the current state of privatbin), AFAIK it is not possible in nginx

**Comment by elrido** [comment]
See the [wiki for a community provided method of restricting access using nginx](https://github.com/PrivateBin/PrivateBin/wiki/Restrict-upload-using-NGINX). It limits the access based on anything but GET & HEAD requests. Those are the only ones used by a viewer, all other methods (like POST or PUT) are only used to create content.

**Comment by parisni** [comment]
My use case differs from the provided link:
- i use nginx as a reverse proxy on a privatebin Docker container
- i don't use basic auth but sso though vouch


Nevertheless i will dig your suggestion to use http verbs GET and POST to restrict usage.

**Comment by parisni** [comment]
@elrido I can't use such approach which only works for `auth_basic`. And the vouch sso authent rely on `auth_request`.


The idea is to add a link base path on the fly which is not protected by the sso. So when one share a paste such as `https://privatebin.example.org/?foobarbaz` the url is forwarded to `https://privatebin.example.org/link?foobarbaz` which is public.

As a result, all user in the sso (here keycloak) can upload data, and share their url to anyone. 
Here are the steps:


docker-compose.yml with privatebin and vouch
```
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:1.7.4
      #build:
      #  context: .
    ports:
      - "8079:8080"
    volumes:
      - /opt/privatebin/data/data:/srv/data
      - /opt/privatebin/data/cfg:/srv/cfg
      - /opt/privatebin/data/cfg/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  vouch:
    image: quay.io/vouch/vouch-proxy:0.41.0
    ports:
      - "9090:9090"
    volumes:
      - ./config:/config
    restart: unless-stopped
```

./config/config.yml
```
vouch:
  allowAllUsers: true

  cookie:
    secure: false
    domain: privatebin.example.org

oauth:
  # Generic OpenID Connect
  provider: oidc
  client_id: privatebin
  client_secret: secret_key
  auth_url: https://keycloak.example.org/realms/master/protocol/openid-connect/auth
  token_url: https://keycloak.example.org/realms/master/protocol/openid-connect/token
  user_info_url: https://keycloak.example.org/realms/master/protocol/openid-connect/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://privatebin.example.org/vouch/auth
```

privatebin.nginx
```
server {
    listen 443 ssl http2;
    server_name privatebin.example.org;

    ssl_certificate /etc/letsencrypt/live/privatebin.example.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/privatebin.example.org/privkey.pem; # managed by Certbot

    location /auth {
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header Host $http_host;
      proxy_pass http://127.0.0.1:9090/auth;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }
    location /vouch/auth {
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header Host $http_host;
      proxy_pass http://127.0.0.1:9090/auth;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    location /vouch/login {
      proxy_pass http://127.0.0.1:9090/login;
      proxy_set_header Host $http_host;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }
    location /vouch/validate {
      proxy_pass http://127.0.0.1:9090/validate;
      proxy_set_header Host $http_host;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }
    # This location serves all Vouch Proxy endpoints as /vouch/$uri
    #   including /vouch/validate, /vouch/login, /vouch/logout, /vouch/auth, /vouch/auth/$STATE, etc
    location /vouch {
      proxy_pass http://localhost:9090; # must not! have a slash at the end
      proxy_set_header Host $http_host;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    # if /vouch/validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 https://privatebin.example.org/vouch/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    location /manifest.json {
      auth_request off;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location /i18n {
      auth_request off;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location /img {
      auth_request off;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location /css {
      auth_request off;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location /js {
      auth_request off;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location / {
        if ($query_string ~ "^[a-z0-9]+$") {
            # Perform the redirect while preserving the query string
            return 301 /link?$query_string;
        }
      auth_request /vouch/validate;
      proxy_pass  http://127.0.0.1:8079;
      # see the Nginx config above for additional headers which can be set from Vouch Proxy
    }
    location /link {
        if ($query_string = "") {
                #return 404;  # Return 404 or handle the case when there is no query string
            return 301 /;
        }
      auth_request 'off';
      proxy_pass  http://127.0.0.1:8079;
    }
}

```
