### ISSUE TITLE
'Could not create paste: server error or not responding'

### ISSUE THREAD

**Issue by skywardgaze** [PrivateBin/PrivateBin#475]
## Steps to reproduce

I have the latest version of PrivateBin pulled and running as a docker image fronted by Traefik. My compose file looks as follows. I've tried running the image without Traefik fronting it and seem to run into the same issue.

```
version: '3'

services:
  privatebin:
    container_name: privatebin
    image: privatebin/nginx-fpm-alpine:latest
    restart: always
    volumes:
      - ${PWD}/data:/srv/data
    networks:
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:xxx.xxx.xxx"
      - "traefik.port=80"
      - "traefik.docker.network=webproxy"

networks:
  webproxy:
    external: true
```

### What happens
When I try to create a paste I get an error saying
`Could not create paste: server error or not responding`.

When I look in the Browser Console I see that network requests to the backend result in a 500 Internal Server Error, not much more information is present. The logs on the PrivateBin server are totally empty as well. 

**Browser:** Firefox 68.0.1
