### ISSUE TITLE
Docker-compose S6-MKDIR issue

### ISSUE THREAD

**Issue by alphat5** [PrivateBin/PrivateBin#587]
## Steps to reproduce

1. Create a docker-compose file (see my file content bellow)
2. run docker-compose up

### What happens
Receive the following error:
`s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied`

### What should happen
The container should run and be accessible online

## Additional information
docker-compose
```
version: "3.2"
services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    user: 65534:82
    environment:
      - VIRTUAL_HOST=ssm.domain.ovh
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ssm.domain.ovh
      - VIRTUAL_NETWORK=nginx-proxy
    volumes:
      - source: data
        target: /srv/data
        type: volume
    expose:
      - 8080
    restart: unless-stopped

networks:
   default:
      external:
        name: reverse

volumes:
  data: ~
```
I also tried to run as superuser, set the owner of the volume folder to 65534:82. And both didn't help to solve the problem. Does someone have an idea to solve this issue please?

## Basic information

**Server OS:**Debian 9

**Webserver:** Nginx 1.17.5 (Docker Container)

**PrivateBin version:** Latest Docker Version

I can reproduce this issue on <https://privatebin.net>: No
