### ISSUE TITLE
Enhancement: add "font-display:swap"

### ISSUE THREAD

**Issue by Forza-tng** [PrivateBin/PrivateBin#758]
According to <https://web.dev/font-display/> It is good practice to add `font-display:swap` so that text remains visible during font download

It could be put in the `@font-face` section in `bootstrap.css`.
 
```css
 @font-face{
	font-family:"Glyphicons Halflings";
	src:url(fonts/glyphicons-halflings-regular.woff2) format("woff2")
	font-display:swap;
 }
```

Also, do you have an un-minified version of bootstrap?
